eureka:
    instance:
        hostname: localhost
    client:  # Not a client, don't register with yourself
        registerWithEureka: false
        fetchRegistry: false

server:
    port: 8001   # HTTP (Tomcat) port

        # Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
    thymeleaf:
        cache: false